import Head from 'next/head';
import Image from 'next/image';
import { useSelector } from 'react-redux';
import Navbar from '../components/Navbar';
import CounterRed from '../components/CounterRed';
// import Decrement from '../components/Decrement';
// import Increment from '../components/Increment';

export default function Counter() {
	const count = useSelector((state) => state.counter.value);

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<CounterRed />
			{/* <Increment />
			<Decrement /> */}
		</div>
	);
}
